version: "3.8"
services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - API_KEY=your_default_key
    depends_on:
      - redis

  redis:
    image: redis:7
    ports:
      - "6379:6379"
